name: Build init

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28

      - name: Build init
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang \
            init.c \
            -O2 \
            -o init

      - name: Check binary
        run: |
          file init
          readelf -h init

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: init
          path: init
